apiVersion: apps/v1
kind: Deployment
metadata:
  name: ledger-service
  namespace: swiftpay
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ledger-service
  template:
    metadata:
      labels:
        app: ledger-service
    spec:
      containers:
        - name: ledger-service
          image: swiftpay/ledger-service:latest
          ports:
            - containerPort: 8082
          env:
            - name: SERVER_PORT
              value: "8082"
            - name: SPRING_PROFILES_ACTIVE
              value: docker
