apiVersion: v1
kind: Service
metadata:
  name: ledger-service
  namespace: swiftpay
  labels:
    app: ledger-service
    app.kubernetes.io/name: swiftpay
    app.kubernetes.io/part-of: payment-ledger
spec:
  type: ClusterIP
  selector:
    app: ledger-service
  ports:
    - name: http
      port: 8082
      targetPort: 8082
