server:
  port: 8082

spring:
  application:
    name: service-b-ledger

  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:swiftpay_ledger}
    username: ${DB_USER:swiftpay}
    password: ${DB_PASSWORD:swiftpay}
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true
    locations: classpath:db/migration

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    consumer:
      group-id: ledger-service
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      auto-offset-reset: earliest
      enable-auto-commit: false   # manual ack after DB commit — see docs/DESIGN.md section 8
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      acks: all
    listener:
      ack-mode: manual_immediate

swiftpay:
  kafka:
    topics:
      payment-initiated: payment-initiated
      payment-completed: payment-completed
      payment-failed: payment-failed
      payment-initiated-dlq: payment-initiated-dlq
    consumer:
      max-retry-attempts: 3
      retry-backoff-ms: 500

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      show-details: always

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} [txId=%X{transactionId}] - %msg%n"
