spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/swift_pay_txn_gateway}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:root}
    driver-class-name: org.postgresql.Driver

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      connect-timeout: 2s
      timeout: 2s

swiftpay:
  ledger:
    base-url: ${LEDGER_SERVICE_URL:http://localhost:8082}

logging:
  level:
    root: INFO
    com.swiftpay: INFO
