server:
  port: ${SERVER_PORT:8081}

spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://postgres:5432/swift_pay_txn_gateway}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:root}
    driver-class-name: org.postgresql.Driver

swiftpay:
  ledger:
    base-url: ${LEDGER_SERVICE_URL:http://ledger-service:8082}

logging:
  level:
    root: INFO
    com.swiftpay: INFO
