
services:
  postgres:
    image: postgres:18
    container_name: swiftpay-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_MULTIPLE_DATABASES: swift_pay_txn_gateway,swiftpay_ledger,swiftpay_analytics
    volumes:
      - pgdata:/var/lib/postgresql
      - ./infra/init-multiple-dbs.sh:/docker-entrypoint-initdb.d/init-multiple-dbs.sh
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
      interval: 5s
      timeout: 5s
      retries: 20

  redis:
    image: redis:7-alpine
    container_name: swiftpay-redis
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 10

  zookeeper:
    image: confluentinc/cp-zookeeper:7.6.1
    container_name: swiftpay-zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:7.6.1
    container_name: swiftpay-kafka
    depends_on:
      zookeeper:
        condition: service_started
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:29092,PLAINTEXT_HOST://0.0.0.0:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
    healthcheck:
      test: ["CMD", "kafka-topics", "--bootstrap-server", "localhost:9092", "--list"]
      interval: 10s
      timeout: 10s
      retries: 20

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: swiftpay-kafka-ui
    depends_on:
      kafka:
        condition: service_healthy
    ports:
      - "8090:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: swiftpay-local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:29092

  transaction-gateway:
    build:
      context: .
      dockerfile: transaction-gateway/Dockerfile
    container_name: swiftpay-transaction-gateway
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      kafka:
        condition: service_healthy
    environment:
      SERVER_PORT: 8081
      SPRING_PROFILES_ACTIVE: docker
      DB_URL: jdbc:postgresql://postgres:5432/swift_pay_txn_gateway
      DB_USERNAME: postgres
      DB_PASSWORD: root
      REDIS_HOST: redis
      REDIS_PORT: 6379
      KAFKA_BOOTSTRAP_SERVERS: kafka:29092
      KAFKA_CONSUMER_GROUP: transaction-gateway
      LEDGER_SERVICE_URL: http://ledger-service:8082
    ports:
      - "8081:8081"

  ledger-service:
    build:
      context: .
      dockerfile: ledger-service/Dockerfile
    container_name: swiftpay-ledger-service
    depends_on:
      postgres:
        condition: service_healthy
      kafka:
        condition: service_healthy
    environment:
      SERVER_PORT: 8082
      SPRING_PROFILES_ACTIVE: docker
      DB_URL: jdbc:postgresql://postgres:5432/swiftpay_ledger
      DB_USERNAME: postgres
      DB_PASSWORD: root
      KAFKA_BOOTSTRAP_SERVERS: kafka:29092
      KAFKA_CONSUMER_GROUP: ledger-service
    ports:
      - "8082:8082"

  analytics-worker:
    build:
      context: .
      dockerfile: analytics-worker/Dockerfile
    container_name: swiftpay-analytics-worker
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      kafka:
        condition: service_healthy
    environment:
      SERVER_PORT: 8083
      SPRING_PROFILES_ACTIVE: docker
      ANALYTICS_DB_URL: jdbc:postgresql://postgres:5432/swiftpay_analytics
      ANALYTICS_DB_USERNAME: postgres
      ANALYTICS_DB_PASSWORD: root
      ANALYTICS_DB_DRIVER_CLASS_NAME: org.postgresql.Driver
      REDIS_HOST: redis
      REDIS_PORT: 6379
      KAFKA_BOOTSTRAP_SERVERS: kafka:29092
      KAFKA_CONSUMER_GROUP_ID: analytics-worker-group
    ports:
      - "8083:8083"

volumes:
  pgdata:
