apiVersion: v1
kind: Secret
metadata:
  name: swiftpay-db-secret
  namespace: swiftpay
  labels:
    app.kubernetes.io/name: swiftpay
    app.kubernetes.io/part-of: payment-ledger
type: Opaque
stringData:
  DB_USERNAME: "postgres"
  DB_PASSWORD: "root"
  ANALYTICS_DB_USERNAME: "postgres"
  ANALYTICS_DB_PASSWORD: "root"
  REDIS_PASSWORD: ""
