apiVersion: apps/v1
kind: Deployment
metadata:
  name: analytics-worker
  namespace: swiftpay
spec:
  replicas: 1
  selector:
    matchLabels:
      app: analytics-worker
  template:
    metadata:
      labels:
        app: analytics-worker
    spec:
      containers:
        - name: analytics-worker
          image: swiftpay/analytics-worker:latest
          ports:
            - containerPort: 8083
          env:
            - name: SERVER_PORT
              value: "8083"
            - name: SPRING_PROFILES_ACTIVE
              value: docker
