spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/swiftpay_ledger}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:root}
    driver-class-name: org.postgresql.Driver

logging:
  level:
    root: INFO
    com.swiftpay: INFO
